import {
  SFNClient,
  StartExecutionCommand,
  DescribeExecutionCommand,
  GetActivityTaskCommand,
  SendTaskSuccessCommand,
} from '@aws-sdk/client-sfn'

const sfn = new SFNClient({
  endpoint: process.env.AWS_ENDPOINT_URL,
  region: process.env.AWS_REGION || 'us-east-1',
  credentials: {
    accessKeyId: process.env.AWS_ACCESS_KEY_ID || 'test',
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY || 'test',
  },
})

const STATE_MACHINE_ARN = process.env.STEP_FUNCTIONS_STATE_MACHINE_ARN ||
  'arn:aws:states:us-east-1:000000000000:stateMachine:RenderPipeline-local'

describe('Step Functions (LocalStack)', () => {
  test('state machine can be started with a valid input payload', async () => {
    const result = await sfn.send(new StartExecutionCommand({
      stateMachineArn: STATE_MACHINE_ARN,
      input: JSON.stringify({ jobId: 'test-123', userId: 'user-456' }),
    }))

    expect(result.executionArn).toBeDefined()
    expect(result.startDate).toBeDefined()
  })

  test('execution can be described after start', async () => {
    const start = await sfn.send(new StartExecutionCommand({
      stateMachineArn: STATE_MACHINE_ARN,
      input: JSON.stringify({ jobId: 'test-describe', userId: 'user-describe' }),
    }))

    const desc = await sfn.send(new DescribeExecutionCommand({
      executionArn: start.executionArn!,
    }))

    expect(desc.status).toBeDefined()
    expect(desc.stateMachineArn).toBe(STATE_MACHINE_ARN)
  })

  // .todo — requires state-machine.asl.json generated by infra/scripts/generate-local-asl.ts
  // (script does not exist yet)
  test.todo('WaitForSlot callback pauses execution until SendTaskSuccess')

  test.todo('SendTaskSuccess on WaitForSlot task token advances to GrantSlot')

  test.todo('State machine reaches Succeed when all callbacks resolved')

  test.todo('Routes to ReleaseCreditsAndFail on callback timeout')
})
